---
title: Reading List
---

## ADS

### Basic & Light Reading

* Unlocking Algorithms. Cormen
* First Course in Algorithms Through Puzzles. Uehara

### Intermediate

* Understanding Algorithms and Data Structures. Brunksill
* Algorithms + Data Structures = Programs. Wirth
* Problems on Algorithms. Ian Parberry
* Fundamentals of Algorithmics. Brassard, Bratley
* Foundations of Algorithms. Neapolitan
* Data Structures and Algorithms - a First Course. Adamson
* Algorithms and Data Structures - Design, Correctness, and Analysis. Kingston
* Data Structures and Their Algorithms. Lewis, Denenberg
* Design and Analysis of Algorithms. Smith

### Python

* Data Structures and Algorithms in Python. Lafore
* Fundamentals of Python Data Structures. (2nd ed). Kenneth Lambert
* Competitive Programming in Python. Duerr

### C

* Algorithms and Data Structures - an Approach in C. 
* Programs and Data Structures in C. Ammeraal
* Foundations of Computer Science. Ullman

### C++ 

* Data Structures and Algorithm Analysis in C++. Weiss
* Data Structures and Problem Solving using C++. Weiss
* Principles of Algorithmic Problem Solving. Sannemo
* Problem Solving in Data Structures & Algorithms Using C++. Hemant Jain

### Java

* Fundamentals of OOP and Data Structures in Java. Wiener

### Advanced 

* How to Think About Algorithms. Jeff Edmonds
* Basic Toolbox. Melhorn 
* Algorithms. Erickson


## Discrete Math and Graph Theory

1. Mathematical Structures for Computer Science. Judith Gersting
   1. 3: Recurrence Relations & Analysis of Algorithms
   2. 5: Graphs & Trees
   3. 7: Graph Algorithms
2. Discrete Mathematics. Rosen
   3: Algorithms
   5: Induction & Recursion
   8: Advanced Counting: recurrence relations
   10: Graphs 
   11: Trees
3. Discrete & Combinatorial Mathematics
   1. 4: Mathematical Induction
   2. 5.7, 5.8: Analysis of Algorithms
   3. 10: Recurrence Relations
   4. 11, 12, 13: Graph Theory
4. Diskrete Mathematik fuer Einsteiger. Beutelspacher
5. Discrete Mathematics in Computer Science. Golovnev, Kulikov
6. Concrete Mathematics. Knuth

### Graph Specific 

1. Graph Theory - A Problem Oriented Approach. Daniel Marcus
2. Algorithmic Graph Theory. Alan Gibbons